{ 
  NAME: "SPELL: ANIMATE DEAD", 
  DESCRIPTION: "",
  SEQUENCE: 2,
  COST: "3 FP",
  RANGE: "10 FEET",
  COMPONENTS: "V,S,M",
  DURATION: "INSTANTANEOUS",
  CONCENTRATION: false,
  REQUIREMENTS: "SPELLCASTING: NECROMANCY",
  AVAILABLE: (f, c) => hasFeature("SPELLCASTING: NECROMANCY"),
  APPLY_STATS: (f, c) => {},
  APPLY_FEATURE: (f, c) => { c.ADDITIONAL_FEATURES.push(f); },
  TAGS: [ "SPELLCASTING", "NECROMANCY", "SPELL" ]
}
